name: CICD
on: 
  pull_request:
    branches: 
      - "main"      
      - "develop"     
    types: [closed]  
    paths-ignore: 
      - ops/deploy/*    
  workflow_dispatch:

jobs:
    CI:
       runs-on: ubuntu-latest
       steps: 
       - name: Obtendo o código
         uses: actions/checkout@v4.1.5 

    CD-Dev:
      # Condição para rodar somente se o PR for para a branch develop
      if: github.ref == 'refs/heads/develop'
      needs: [CI]
      uses: wallafidevops/pro-gitops-argocd/.github/workflows/dev.yml@develop 
      with:
        environment: dev
      secrets: inherit


    CD-Prod:
      # Condição para rodar somente se o PR for para a branch main
      if: github.ref == 'refs/heads/main'
      needs: [CI]
      uses: wallafidevops/pro-gitops-argocd/.github/workflows/prod.yml@main    
      with:
        environment: prod
      secrets: inherit         

     